# Generated by Django 3.2.7 on 2021-10-28 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0004_alter_myuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_on', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionaires', to='account.psychiatrist')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=6144)),
                ('answer_type', models.CharField(choices=[('RANGE', 'RANGE'), ('SHORTANSWER', 'SHORTANSWER')], max_length=20)),
                ('min', models.IntegerField(blank=True, null=True)),
                ('max', models.IntegerField(blank=True, null=True)),
                ('min_label', models.CharField(blank=True, max_length=3072, null=True)),
                ('max_label', models.CharField(blank=True, max_length=3072, null=True)),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='psychiatrist.questionnaire')),
            ],
        ),
    ]
