# Generated by Django 3.2.7 on 2021-10-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychiatrist', '0002_auto_20211028_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer_type',
            new_name='type',
        ),
    ]
