# Generated by Django 3.2.7 on 2021-10-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychiatrist', '0003_rename_answer_type_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
