# Generated by Django 3.2.7 on 2021-10-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychiatrist', '0004_questionnaire_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='title',
            field=models.CharField(default='', max_length=4096),
        ),
    ]
