# Generated by Django 3.2.7 on 2021-10-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychiatrist', '0005_questionnaire_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='title',
            field=models.CharField(max_length=4096),
        ),
    ]
