# Generated by Django 3.2.7 on 2021-11-07 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psychiatrist', '0009_auto_20211102_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='response',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='psychiatrist.questionnaireresponses'),
            preserve_default=False,
        ),
    ]
