# Generated by Django 3.2.7 on 2021-11-13 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_psychiatrist_rating'),
        ('psychiatrist', '0013_blogpost_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('remedy', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_reports', to='account.psychiatrist')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='account.patient')),
            ],
        ),
    ]
