# Generated by Django 3.2.7 on 2021-11-13 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_psychiatrist_rating'),
        ('psychiatrist', '0014_questionnairereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('remedy', models.TextField()),
                ('writen_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_reports', to='account.psychiatrist')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='account.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionnaireReport',
        ),
    ]
