# Generated by Django 3.2.7 on 2021-11-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychiatrist', '0016_auto_20211113_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreport',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
