# Generated by Django 3.2.7 on 2021-11-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychiatrist',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
