# Generated by Django 3.2.7 on 2021-11-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_myuser_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychiatrist',
            name='rating',
        ),
    ]
