# Generated by Django 3.2.7 on 2021-11-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_psychiatrist_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
