# Generated by Django 3.2.7 on 2021-10-18 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20211016_1627'),
        ('patients', '0002_auto_20211017_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlike',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.patient'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.post'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=4096)),
                ('is_public', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.psychiatrist')),
            ],
        ),
    ]
