# Generated by Django 3.2.7 on 2021-10-23 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_myuser_managers'),
        ('patients', '0004_community_communitymember_communitymessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('EXPIRED', 'EXPIRED'), ('DRAFT', 'DRAFT'), ('DONE', 'DONE')], max_length=10)),
                ('time', models.DateTimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to='account.patient')),
                ('with_who', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_with', to='account.psychiatrist')),
            ],
        ),
    ]
