# Generated by Django 3.2.7 on 2021-10-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('EXPIRED', 'EXPIRED'), ('DRAFT', 'DRAFT'), ('DONE', 'DONE')], default='PENDING', max_length=10),
        ),
    ]
