# Generated by Django 3.2.7 on 2021-10-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('EXPIRED', 'EXPIRED'), ('DRAFT', 'DRAFT'), ('DONE', 'DONE'), ('BOOKED', 'BOOKED')], default='PENDING', max_length=10),
        ),
    ]
