# Generated by Django 3.2.7 on 2021-10-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_myuser_phone_number'),
        ('patients', '0007_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.psychiatrist'),
            preserve_default=False,
        ),
    ]
