# Generated by Django 3.2.7 on 2021-10-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_community_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
