# Generated by Django 3.2.7 on 2021-10-27 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_post_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
