# Generated by Django 3.2.7 on 2021-10-27 15:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_rename_create_at_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymessage',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
