# Generated by Django 3.2.7 on 2021-11-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='meeting_link',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
