# Generated by Django 3.2.7 on 2021-11-03 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_alter_appointment_meeting_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='time',
        ),
    ]
